theme: jekyll-theme-slate 
title:  MY ZONE # to be filled in by you
description: ç«‹ã¡å…¥ã‚Šç¦æ­¢ğŸš§ # to be filled in by you
plugins: 
    - jemoji 
url: "https://ulysseschill.github.io/" 
markdown: kramdown
